Allow starting without Elasticsearch.
zammad/zammad-docker-compose pull request #171
Opened 2020-09-09 12:31 UTC by jgoclawski

Hi team,

I'm not sure if it's something that you would like to merge considering the discussion in #160, but I found that option really useful. At the moment our company uses a forked version of this Docker image, so I thought that I'd try upstreaming our changes.

Reasons to support running the image without Elasticsearch:
1. Elasticsearch is a soft (strongly recommended!) dependency for Zammad. But it's not a hard one, so there's no reason why the Docker image should change the requirements. It should have the same requirements as DEBs or RPMs.
2. Adding such option to the image is very simple, doesn't add much maintentance cost in the future and some people might find it useful.
3. Some people run a small installation of Zammad and it works perfectly OK without ES and the only drawback is that reports are not available.
4. It could be used as a fallback mode. Let's imagine an outage of ES cluster (which happens from time to time in real life). A sysadmin could then temporarily restart Zammad without ES, until the problem with ES is fixed. It could also be useful when upgrading ES cluster as well.

2020-09-11 23:08 UTC, monotek requested changes
Could you ease also add some documentation to the readme how to use it as compose file needs to be modified to for that.

2020-09-14 12:54 UTC, jgoclawski commented
@monotek Hi, I've added a paragraph to the readme. Please let me know if that works for you. 
I was thinking about adding an example to `.examples` directory as well, but you'd have to remember to update it if other settings change in the future. So in the end I think a paragraph in the readme is enough and it's easier to maintain.

2020-09-14 14:11 UTC, monotek approved these changes

2020-09-14 14:11 UTC, merged

2020-09-14 14:45 UTC, jgoclawski commented
Thanks!