Fixes #205 - Automatically remove IPv6 listen directive
zammad/zammad-docker-compose pull request #207
Opened 2021-04-23 17:46 UTC by MrGeneration

This pull request addresses issue #205 which was introduced due to issue #3371 of the main zammad repo.

It removes the IPv6 listen directive *before* replacing listen directives which currently causes duplicate listen directives and thus results in crashing nginx containers.

2021-04-24 10:30 UTC, monotek requested changes
```
s#\(listen\)\(.*\)80#\1\28080#g"
```

2021-04-24 10:30 UTC, monotek commented on containers/zammad/docker-entrypoint.sh
> +      -e "s#listen .*#listen ${NGINX_PORT};#g" \
The new regex is superfluous. We can do this in the existing line, using the same ipv6 config in the container as well:

```
s#\(listen\)\(.*\)80#\1\2${NGINX_PORT}#g"
```

2021-04-24 13:07 UTC, monotek approved these changes

2021-04-24 13:19 UTC, monotek approved these changes

2021-04-24 13:20 UTC, merged

2021-04-25 11:15 UTC, rvalle commented
@monotek I just installed Zammad for first time. 

Can you release this patch to the docker image? 

I think it the currently published image is not functional without this fix.

2021-04-25 11:31 UTC, rvalle commented
I saw the ```sed```  workaround now...

2021-04-25 12:15 UTC, monotek commented
The image is build as soon as new commits arrive in the stable branch of https://github.com/zammad/zammad