timed backup script with backup time
zammad/zammad-docker-compose pull request #339
Opened 2023-05-03 15:26 UTC by migasQ

- fixed backup time
- dynamic sleep based on duration of previous backup

2023-05-10 11:14 UTC, monotek requested changes
please fix ci

2023-05-10 11:14 UTC, monotek commented on docker-compose.yml
> +    command: ["zammad-timed-backup"]
please keep old command

2023-05-10 11:14 UTC, monotek commented on scripts/backup.sh
> +if [ "$1" = 'zammad-timed-backup' ]; then
lets make that the default.
so command name should be "zammad-backup"

2023-05-12 15:41 UTC, monotek commented on scripts/backup.sh
> +  until (echo > "/dev/tcp/$ZAMMAD_RAILSSERVER_HOST/$ZAMMAD_RAILSSERVER_PORT") &> /dev/null; do
why was this changed?

2023-05-12 18:09 UTC, migasQ commented
Because the bash script linter complained about this line. I can reverse it but then the linter will keep failing. Am 12.05.2023 um 17:41 schrieb André Bauer ***@***.***>:﻿
@monotek commented on this pull request.



In scripts/backup.sh:
> @@ -11,7 +11,7 @@ set -e
 : "${POSTGRESQL_DB:=zammad_production}"
 
 function check_railsserver_available {
-  until (echo > /dev/tcp/${ZAMMAD_RAILSSERVER_HOST}/${ZAMMAD_RAILSSERVER_PORT}) &> /dev/null; do
+  until (echo > "/dev/tcp/$ZAMMAD_RAILSSERVER_HOST/$ZAMMAD_RAILSSERVER_PORT") &> /dev/null; do

why was this changed?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-05-12 18:51 UTC, monotek approved these changes

2023-05-12 18:51 UTC, merged